import { StyleSheet } from 'react-native';
import { C, R } from '@/theme/colors';
import { F } from '@/theme/typography';

export const adminStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg },
  padded: { padding: 16, paddingBottom: 40 },
  card: {
    backgroundColor: C.surface,
    borderRadius: R.lg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    padding: 14,
    marginBottom: 10,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  title: {
    color: C.text,
    fontSize: 16,
    fontFamily: F.serif,
    fontWeight: '600',
    flex: 1,
  },
  meta: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.sans,
    marginTop: 4,
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: R.sm,
    backgroundColor: C.bg3,
  },
  chipText: {
    fontSize: 10,
    fontFamily: F.sans,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: C.textSub,
  },
  input: {
    backgroundColor: C.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    borderRadius: R.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: C.text,
    fontFamily: F.sans,
    marginBottom: 10,
  },
  label: {
    color: C.textSub,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontFamily: F.sans,
    marginBottom: 6,
  },
  section: {
    color: C.textMuted,
    fontSize: 11,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    fontFamily: F.sans,
    marginTop: 8,
    marginBottom: 10,
  },
  actions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  actionBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: R.md,
    backgroundColor: C.primarySoft,
  },
  actionBtnDanger: {
    backgroundColor: C.accentSoft,
  },
  actionText: {
    color: C.primary,
    fontSize: 12,
    fontFamily: F.sans,
    fontWeight: '600',
  },
  actionTextDanger: {
    color: C.ruby,
  },
  empty: {
    textAlign: 'center',
    color: C.textMuted,
    marginTop: 40,
    fontFamily: F.sans,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  kpi: {
    width: '47%',
    backgroundColor: C.surface,
    borderRadius: R.lg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    padding: 14,
  },
  kpiValue: {
    color: C.text,
    fontSize: 22,
    fontFamily: F.serif,
    fontWeight: '600',
  },
  kpiLabel: {
    color: C.textMuted,
    fontSize: 11,
    marginTop: 4,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    fontFamily: F.sans,
  },
});
